#ifndef COLOR_H
#define COLOR_H

#ifdef _WIN32
#include <Windows.h>

enum Colors
{
	COLOR_FOREGROUND_RED = FOREGROUND_RED,
	COLOR_FOREGROUND_GREEN = FOREGROUND_GREEN,
	COLOR_FOREGROUND_BLUE = FOREGROUND_BLUE,
	COLOR_FOREGROUND_INTENSE = FOREGROUND_INTENSITY,

	COLOR_BACKGROUND_RED = BACKGROUND_RED,
	COLOR_BACKGROUND_GREEN = BACKGROUND_GREEN,
	COLOR_BACKGROUND_BLUE = BACKGROUND_BLUE,
	COLOR_BACKGROUND_INTENSE = BACKGROUND_INTENSITY,

	COLOR_DEFAULT = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_INTENSITY
};

#else
#error Platforms other than Windows are not supported yet
#endif // _WIN32
#endif // COLOR_H